apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - selfcertificate.yaml
  - istio-manifests.yaml
  - ingress-backendconfig.yaml
  - managed-cert.yaml
  - frontend-config.yaml
  - ingress.yaml
  # - ingress-internal.yaml
patchesStrategicMerge:
  - https-gateway.yaml
